### ISSUE TITLE
Qibla Direction - Example

### ISSUE THREAD

**Issue by ahamedsaifudeen** [batoulapps/adhan-swift#10]
I am happy to know that this library includes the qibla direction. Can you include an example of how to display the qibla direction image based on the qibla angle returned by the library? I think it is good idea to include a UI component (UIViewController) on this library to display the Qibla direction. Things gets better when we have more contributors rather than individual developers handling it differently.

**Comment by z3bi** [comment]
Including a UI component is really outside of the scope of this library. This library is multi-platform (iOS, watchOS, tvOS, and macOS) which makes it complicated to know what are the appropriate APIs to call. Also, there isn't really a standard UI element for displaying direction, it would probably be the best interest of each app developer to use their own styles to display the Qibla direction.

For an example on iOS, you could do something like the following to display the direction using an image. For more information read the docs on [CGAffineTransform](https://developer.apple.com/documentation/coregraphics/cgaffinetransform)
```
let myImageView = UIImageView(image: myArrowImage)
let qibla = Qibla(coordinates: myCoordinates).direction
let radians = qibla * (.pi/180)
myImageView.transform = CGAffineTransform(rotationAngle: CGFloat(radians))
```

**Comment by ahamedsaifudeen** [comment]
Thanks for the response. Can you also guide me on how to rotate the compass image? The image is shown below. I have a pointer image for which I will use your above code. 

[
<img width="711" alt="screenshot 2018-10-13 at 12 53 51 pm" src="https://user-images.githubusercontent.com/3712366/46901476-38c4f800-cee7-11e8-93d5-8222b0633961.png">
](url)

**Comment by z3bi** [comment]
@ahamedsaifudeen that's really outside of the scope of the library, there are many great tutorials online showing how to do that, here is one example: https://medium.com/swiftly-swift/how-to-build-a-compass-app-in-swift-2b6647ae25e8

**Comment by Mannopson** [comment]
> Including a UI component is really outside of the scope of this library. This library is multi-platform (iOS, watchOS, tvOS, and macOS) which makes it complicated to know what are the appropriate APIs to call. Also, there isn't really a standard UI element for displaying direction, it would probably be the best interest of each app developer to use their own styles to display the Qibla direction.
> 
> For an example on iOS, you could do something like the following to display the direction using an image. For more information read the docs on [CGAffineTransform](https://developer.apple.com/documentation/coregraphics/cgaffinetransform)
> 
> ```
> let myImageView = UIImageView(image: myArrowImage)
> let qibla = Qibla(coordinates: myCoordinates).direction
> let radians = qibla * (.pi/180)
> myImageView.transform = CGAffineTransform(rotationAngle: CGFloat(radians))
> ```

I am very happy with this Library, thank you guys! But I don't understand, how to use Qibla direction. Doesn't rotate correctly
