### ISSUE TITLE
Adhan-Swift.h not found 

### ISSUE THREAD

**Issue by aqkhana2002** [batoulapps/adhan-swift#16]
i was using Pod

in debug its working fine but when i do release having this issue. please help.

could not build Objective-C module 'Adhan'

Showing All Messages
/Users/aqeelahmed/Library/Developer/Xcode/DerivedData/eQuranTags-fmtihfgxddcjqugibupjryubkyxi/Build/Products/Release-iphonesimulator/Adhan/Adhan.framework/Modules/module.modulemap:9:12: Header 'Adhan-Swift.h' not found

Could not build Objective-C module 'Adhan'

following file have issue i believe that should be "Adhan.h"

framework module Adhan {
  umbrella header "Adhan-umbrella.h"

  export *
  module * { export * }
}

module Adhan.Swift {
    header "Adhan-Swift.h"
    requires objc
}

**Comment by aqkhana2002** [comment]
<img width="1434" alt="Screen Shot 2019-04-12 at 9 16 56 pm" src="https://user-images.githubusercontent.com/5283983/56033700-71477080-5d68-11e9-8769-eea2c2734cdf.png">

**Comment by aqkhana2002** [comment]
ok have notice my App do have Daily Extension, i am not able to use Adhan in it. any idea ?

**Comment by z3bi** [comment]
In your pod file make sure to include Adhan under the target of your extension as well. Like so:
```
target 'MyApp' do
  pod 'Adhan'
end

target 'MyAppExtension' do
    pod 'Adhan'
end
```

**Comment by aqkhana2002** [comment]
thanks brother for your Quick Response. and i solved the issue
