### ISSUE TITLE
Question about calculation method and madhab

### ISSUE THREAD

**Issue by ahsanaasim** [batoulapps/adhan-swift#17]
I have going through the Prayer Times libraries. I loved adhan-swift so far specially the Convenience Utilities. But i have one question in mind....

Does the calculation method and madhab get adjusted automatically according the Coordinates?

As stated here, it should. 
> Instead of manually initializing this struct it is recommended to use one of the pre-populated instances by calling the params var on the CalculationMethod enum

But i got shafi asr prayer times in Bangladesh location. Did i miss anything here? I guess i need to use one of the CalculationMethod from the table. But i need a direction on detecting the CalculationMethod according to the Coordinates.

**Comment by z3bi** [comment]
I'm glad you like adhan-swift. To address your question, we do not yet auto-suggest a method based on your location. For one, this generally requires a geocode to get the country and feels like a heavier integration than I feel like a library should be doing. 

One way we could potentially do it is to have a convenience function in the CalculationMethod enum that would take a country code and return a value. However, the reason I haven't yet done this is that it makes a lot of assumptions. I am ok making these assumptions in my own app, but making that assumption in a library that other people would assume is validated might be too much. 

For the madhab part of your question, I would probably never suggest madhab based on region as many regions follow multiple madhabs based on the masjid or community.
