### ISSUE TITLE
Something strange

### ISSUE THREAD

**Issue by BassamxMednini** [batoulapps/adhan-swift#18]
As salaamu aleykum,

I tested the prayer times for some locations in germany. I've noticed that some prayer times are most likely incorrect. For example Berlin:

        let cal = Calendar(identifier: Calendar.Identifier.gregorian)
        let date = cal.dateComponents([.year, .month, .day], from: Date())
        let coordinates = Coordinates(latitude: 52.5186015, longitude: 13.4092129)
        var params = CalculationMethod.muslimWorldLeague.params
        params.madhab = .hanafi
        if let prayers = PrayerTimes(coordinates: coordinates, date: date, calculationParameters: params) {
            let formatter = DateFormatter()
            formatter.timeStyle = .medium
            formatter.timeZone = TimeZone(identifier: "Europe/Berlin")!
            
            print("fajr \(formatter.string(from: prayers.fajr))")
            print("sunrise \(formatter.string(from: prayers.sunrise))")
            print("dhuhr \(formatter.string(from: prayers.dhuhr))")
            print("asr \(formatter.string(from: prayers.asr))")
            print("maghrib \(formatter.string(from: prayers.maghrib))")
            print("isha \(formatter.string(from: prayers.isha))")
        }

Output: 

> fajr 01:04:00
> sunrise 05:04:00
> dhuhr 13:04:00
> asr 18:30:00
> maghrib 21:03:00
> isha 00:27:00

Fajr is 37 min away from isha? Another example here with Hamburg:

        let cal = Calendar(identifier: Calendar.Identifier.gregorian)
        let date = cal.dateComponents([.year, .month, .day], from: Date())
        let coordinates = Coordinates(latitude: 53.5496505, longitude: 9.9908773)
        var params = CalculationMethod.muslimWorldLeague.params
        params.madhab = .hanafi
        if let prayers = PrayerTimes(coordinates: coordinates, date: date, calculationParameters: params) {
            let formatter = DateFormatter()
            formatter.timeStyle = .medium
            formatter.timeZone = TimeZone(identifier: "Europe/Berlin")!
            
            print("fajr \(formatter.string(from: prayers.fajr))")
            print("sunrise \(formatter.string(from: prayers.sunrise))")
            print("dhuhr \(formatter.string(from: prayers.dhuhr))")
            print("asr \(formatter.string(from: prayers.asr))")
            print("maghrib \(formatter.string(from: prayers.maghrib))")
            print("isha \(formatter.string(from: prayers.isha))")
        }

Output:

> fajr **01:18**:00
> sunrise 05:12:00
> dhuhr 13:18:00
> asr 18:45:00
> maghrib 21:22:00
> isha **01:16**:00

For cities in the south, for example Stuttgart or Munich the output makes more sense:

        // Munich
        let cal = Calendar(identifier: Calendar.Identifier.gregorian)
        let date = cal.dateComponents([.year, .month, .day], from: Date())
        let coordinates = Coordinates(latitude: 48.1382614, longitude: 11.5845093)
        var params = CalculationMethod.muslimWorldLeague.params
        params.madhab = .hanafi
        if let prayers = PrayerTimes(coordinates: coordinates, date: date, calculationParameters: params) {
            let formatter = DateFormatter()
            formatter.timeStyle = .medium
            formatter.timeZone = TimeZone(identifier: "Europe/Berlin")!
            
            print("fajr \(formatter.string(from: prayers.fajr))")
            print("sunrise \(formatter.string(from: prayers.sunrise))")
            print("dhuhr \(formatter.string(from: prayers.dhuhr))")
            print("asr \(formatter.string(from: prayers.asr))")
            print("maghrib \(formatter.string(from: prayers.maghrib))")
            print("isha \(formatter.string(from: prayers.isha))")
        }

> fajr 02:56:00
> sunrise 05:29:00
> dhuhr 13:11:00
> asr 18:29:00
> maghrib 20:52:00
> isha 23:14:00

**Comment by z3bi** [comment]
Perhaps this is something we should go into more in depth in the README, but for location  at higher latitudes (such as above 48 degrees) most scholars recommend using an estimation for Fajr and Isha to avoid hardship, this can be done by setting the `highLatitudeRule` to something like `seventhOfTheNight` (there is also the `angleBased` rule that is present to mimic other calculations, but I am unaware of a scholar suggesting that approach).

**Comment by BassamxMednini** [comment]
`highLatitudeRule` was the key. Thanks.
