### ISSUE TITLE
Next prayer and current payer not working for me.

### ISSUE THREAD

**Issue by nazmulkp** [batoulapps/adhan-swift#19]
let coordinates = Coordinates(latitude: 23.8103, longitude: 90.4125)
        var cal = Calendar(identifier: Calendar.Identifier.gregorian)
        cal.timeZone = TimeZone(identifier: "Asia/Dhaka")!
        let date = cal.dateComponents([.year, .month, .day], from: Date())

        var params = CalculationMethod.karachi.params
        params.madhab = .hanafi
         prayers = PrayerTimes(coordinates: coordinates, date: date, calculationParameters: params)
        
      //below code give me wrong current payer and next prayer
        let current = prayers!.currentPrayer()
        let next = prayers!.nextPrayer()
        let countdown = prayers!.time(for: next!)

in morning time 11.38am where if Dhur will be start from 11:58 am. but it's give current prayer Asar and next prayer is Maghrib  

> current : Optional(Adhan.Prayer.asr)
> next : Optional(Adhan.Prayer.maghrib)
> countdown : 2019-06-06 12:43:00 +0000

**Comment by z3bi** [comment]
Is the time zone of the machine this is running on the same as the time zone of the prayer times? If not this could be what is expected. The way to think about the functionality is that it’s telling you what the current prayer is in that location, regardless of what the clock says for your location.

**Comment by nazmulkp** [comment]
the time zone of the machine this is running on the not same as the time zone of the prayer times.
