### ISSUE TITLE
Add Isha minutes during Ramadan for ummAlQura?

### ISSUE THREAD

**Issue by basememara** [batoulapps/adhan-swift#23]
In the readme, there's a note for `ummAlQura` calculation method: _Note: you should add a +30 minute custom adjustment for Isha during Ramadan._ 

Is this referring to `adjustments` or `methodAdjustments` on `CalculationParameters`.. or does it matter because I couldn't tell those properties are doing anything differently?

https://github.com/batoulapps/adhan-swift/blob/190123bc3f931c273acfad76bd0a913261a90f30/Sources/Models/CalculationParameters.swift#L37

Also wondering, could this not be done automatically in code? A little sketchy but something like this:
https://github.com/batoulapps/adhan-swift/blob/190123bc3f931c273acfad76bd0a913261a90f30/Sources/PrayerTimes.swift#L176
```
self.isha = isha.addingTimeInterval(calculationParameters.adjustments.isha.timeInterval)
    .addingTimeInterval(calculationParameters.methodAdjustments.isha.timeInterval)
    .addingTimeInterval(
        calculationParameters.method == .ummAlQura
            && Calendar(identifier: .islamicUmmAlQura).dateComponents([.month], from: maghrib).month == 9
                ? 30 * 60 : 0
    )
    .roundedMinute()
```

**Comment by z3bi** [comment]
So what I've discovered is that not all masjids who use umm Al-Qura add the extra 30 minutes. So it's not something I wanted to do automatically. Also, based on moonsighting Ramadan may not exactly match the system calendar. Another reason not to do it.

Your comment does bring up a good point as the advice is ambiguous. Really `adjustments` should be used and `methodAdjustments` is meant for internal use only. But this is not enforced or even commented on.

**Comment by basememara** [comment]
That makes perfect sense.

If `methodAdjustments` is internal, shouldn't the `public` access control be removed from it, or is there a reason the caller needs access to it?

**Comment by z3bi** [comment]
Yeah marking it as `public` was a mistake, I'll remove that and it should clear up the ambiguity.
