### ISSUE TITLE
Issue with Singapore Method - Objective C code

### ISSUE THREAD

**Issue by ahamedsaifudeen** [batoulapps/adhan-swift#25]
There is an issue with Singapore method in objective C code in the latest release, can you please check and fix it as soon as possible.

Thread 1: Fatal error: unexpected enum case 'BACalculationMethod(rawValue: 11)'

**Comment by z3bi** [comment]
Can you please post the code you’re using.

**Comment by ahamedsaifudeen** [comment]
BACalculationParameters *params;

    NSDateComponents *date = [cal components:NSCalendarUnitDay|NSCalendarUnitMonth|NSCalendarUnitYear fromDate:prayerTimesDate];
    if ([countryCode isEqualToString:@"SG"])
    {
        params = [[BACalculationParameters alloc] initWithMethod:BACalculationMethodSingapore];
    }

This code works fine with Adhan 1.0.2 but not with 1.1.0

**Comment by z3bi** [comment]
I am unable to reproduce this error. Please try doing a clean build and see if that helps. In version 1.1.0 a new calculation method was added, so it looks like you're code is somehow initing a case that it doesn't have, perhaps because the old enum is still cached.

**Comment by ahamedsaifudeen** [comment]
@z3bi 

It works after clean build. Thank you for the quick response.
