### ISSUE TITLE
Local Notifications

### ISSUE THREAD

**Issue by sabrefm1** [batoulapps/adhan-swift#27]
Hi

I would like to know how I can call the prayer times "time" that the athan will go off. I want to create a local notification for when the time is reached for the prayer (fajr,thur,asr ...)

if i take the example:

func scheduleNotification() {
    let center = UNUserNotificationCenter.current()

    let content = UNMutableNotificationContent()
    content.title = "prayer time"
    content.body = "Time to pray"
    content.categoryIdentifier = "alarm"
    content.sound = UNNotificationSound.default

    var dateComponents = DateComponents()
    dateComponents.hour = 10
    dateComponents.minute = 30
    let trigger = UNTimeIntervalNotificationTrigger(timeInterval: 5, repeats: false)

    let request = UNNotificationRequest(identifier: UUID().uuidString, content: content, trigger: trigger)
    center.add(request)
}

For the date/time components how can i call the time for example fajr. If i try to select fajr for 
   var dateComponents = fajr
this is pointing to my uilabel which is displaying the fajr time and is incomplete as xcode cannot read the data from the uilabel

**Comment by sabrefm1** [comment]
for example if I am using 
fajr.text = "Fajr " + formatter.string(from: prayers.fajr)
to get the value into a uilabel
i cannot get the same value to trigger a notification
let trigger = UNTimeIntervalNotificationTrigger(from: prayers.fajr)

**Comment by sabrefm1** [comment]
> I'm not sure the UILabel is relevant to the issue, but one thing is that `UNTimeIntervalNotificationTrigger` needs a time interval, not a `Date` object which is what `prayers.fajr` would be. You would need to do something like `Date().timeIntervalSince(prayers.fajr)`

where would the Date().timeIntervalSince(prayers.fajr) fir in at the trigger, as I am still failing to get the time recognized as its still seeing it as a date

**Comment by z3bi** [comment]
So you can just do this:
```
let trigger = UNTimeIntervalNotificationTrigger(timeInterval: prayers.fajr.timeIntervalSinceNow, repeats: false)
```

**Comment by sabrefm1** [comment]
Thanks for the help so far. pulling my hair, since the code looks ok. if i set the simulator back to fajr time a minute before fajr is supposed to go off the alarm does not go off at fajr time, in the background or foreground.

**Comment by sabrefm1** [comment]
for example I would like to let the alarm go off at a specified time. So i should use the UNCalendarNotificationTrigger correct? as I want it to go off at a specified time

my code below
`let center = UNUserNotificationCenter.current()
let content = UNMutableNotificationContent()
content.title = "prayer time"
content.body = "Time to pray"
content.categoryIdentifier = "alarm"
content.sound = UNNotificationSound.default

let trigger = UNCalendarNotificationTrigger(dateMatching: prayers.fajr, repeats: false)

let request = UNNotificationRequest(identifier: UUID().uuidString, content: content, trigger: trigger)
center.add(request)
`

but on the trigger line I get error: cannot convert value of type 'Date' to expected argument type 'DateComponents'

**Comment by IsamZareer** [comment]
Is there any update on this?
