### ISSUE TITLE
Objective C no interface for next prayer time

### ISSUE THREAD

**Issue by fatahzull** [batoulapps/adhan-swift#30]
Hi, please help me, there is no interface to get next prayer time objective C.

 BAPrayerTimes *prayerTimes = [[BAPrayerTimes alloc] initWithCoordinates:coordinates date:date calculationParameters:params];

BAPrayerTimes * no available interface for next prayer time. Any help would be greatly appreciated

**Comment by z3bi** [comment]
There is the method `open func nextPrayer(_ time: Date?) -> BAPrayer` on the Objective-C interface. You can call it with `[prayerTimes nextPrayer:nil]` if you pass in nil it will use the current time, otherwise you can specify a time if you want to know the next prayer at a specific point in time.

**Comment by fatahzull** [comment]
@z3bi omG.. my bad sir.. Thank you for helping me out
