### ISSUE TITLE
Adjustment Parameter Usage

### ISSUE THREAD

**Issue by ahamedsaifudeen** [batoulapps/adhan-swift#34]
What is the right way to specify the adjustment for a prayer time in Swift Library? 

To increase:
        params.adjustments.maghrib = 3 or +3?

To decrase:
        params.adjustments.sunrise = -3?

**Comment by z3bi** [comment]
@ahamedsaifudeen the following would be correct:
```
// makes maghrib 3 minutes later
params.adjustments.maghrib = 3

// makes sunrise 3 minutes earlier
params.adjustments.sunrise = -3
```

**Comment by ahamedsaifudeen** [comment]
@z3bi Thank you brother.
