### ISSUE TITLE
Prayer Time is not corrent 

### ISSUE THREAD

**Issue by alauthor** [batoulapps/adhan-swift#36]
in Qatar and Dubai how to use all cases params to make the library get the best result in all cases .

**Comment by z3bi** [comment]
Can you be more specific? What parameters are you using? What times are you getting vs what you are expecting?

**Comment by alauthor** [comment]
var params: CalculationParameters = CalculationMethod.moonsightingCommittee.params
        params.madhab = .shafi
This does not work propeply in ( kuwait, qatar, dubai )

**Comment by alauthor** [comment]
you should handle this via coordinates , you should know in which country the user in 
and start setting the params

**Comment by z3bi** [comment]
@alauthor we have a plan to add in a method that can suggest a calculation method for a country, however it will require a two letter country code, since the library won't have geocoding capabilities built into it.

**Comment by alauthor** [comment]
okay , when this will be done ?

**Comment by z3bi** [comment]
@alauthor I don't have a specific date, mostly because a lot of research is needed to make a comprehensive list. The way this can be started is to try and start a list of regions and links to masajid or official prayer times. That will help us to compile the information we need.
