### ISSUE TITLE
Midnight and Qiyam (Qiyam al-Layl) Prayer time

### ISSUE THREAD

**Issue by natiq2004** [batoulapps/adhan-swift#48]
Assalamu aleykum wa rahmatullahi wa barakatuhu.

It would be better if you add Midnight and Qiyam prayer time. This is very necessary options.

Please look at this: https://github.com/ashikahmad/PrayerTimes-Swift/tree/refactor-calculation

Barakallahu fiik

**Comment by z3bi** [comment]
If you look at the `SunnahTimes` feature, that's exactly what we already have. https://github.com/batoulapps/adhan-swift#sunnah-times
