### ISSUE TITLE
Set AdhanVolume

### ISSUE THREAD

**Issue by natiq2004** [batoulapps/adhan-swift#49]
Assalamu aleykum wa rahmatullahi wa barakatuhu.

It would be better if you add the increase and decrease Adhan Volume for audio files. Because sometimes Adhan voice is very loud.  

// Example
Set AdhanVolume: Default 75%

Barakallahu fiik

**Comment by sgtsquiggs** [comment]
Hi,

I think you have this repo confused for something else. This is a swift library is for calculating Islamic prayer times - It is not an iOS application.
