### ISSUE TITLE
Pre Adhan reminders

### ISSUE THREAD

**Issue by natiq2004** [batoulapps/adhan-swift#50]
Assalamu aleykum wa rahmatullahi wa barakatuhu.

It would be better if you add the Pre Adhan reminders options for each Prayer time. This options is available in most of the Prayer times applications.

Barakallahu fiik

**Comment by z3bi** [comment]
Salam,

This library doesn't include notifications, that would be something that the individual app developer would add to their own application using the times they get from this library.
