### ISSUE TITLE
Qibla finder on Goole Maps

### ISSUE THREAD

**Issue by natiq2004** [batoulapps/adhan-swift#51]
Assalamu aleykum wa rahmatullahi wa barakatuhu.

Apart from Qibla Compass, it is better to integrate Qibla on Google Maps as well. 

Barakallahu fiik

**Comment by sgtsquiggs** [comment]
Hi,

This repo is for adhan-swift, an Islamic prayer time calculation library. It is not an iOS application. It would be up to the developers using this library to implement Google Maps in their own applications.
