### ISSUE TITLE
How to Combine API with another API 

### ISSUE THREAD

**Issue by LaminT** [batoulapps/adhan-swift#55]
As-salâmu ‘alaykum wa Rahmatullâhi wa barakatuhu . I am making a Salah app only for some cities in Denmark. I’m using  a network call with another API with json response. I was wondering is it possible to combine the data I get back from API with your API, so I can use some of your features ? 
I’m very new in Swift, please be patient with me

**Comment by z3bi** [comment]
The fact that you are also using another API shouldn't prevent you from using this library. It would be up to you to decide how to combine the data from the two sets.

**Comment by LaminT** [comment]
I was looking for guidance on how to. I've looked at the documents but I'm too new in Swift to understand it all.

**Comment by SNNafi** [comment]
Then, it it better to learn swift first and then come back again. Because, no one can not guide you throughout the whole process .
 :(
You should learn at least the working level of swift .

**Comment by z3bi** [comment]
@LaminT theres also an example project included in this repo, you can find it here https://github.com/batoulapps/adhan-swift/tree/main/Example/Swift%20Example

Please try using the library and then if you get stuck on a specific problem we can hopefully point you in the right direction

**Comment by LaminT** [comment]
Ok, should I install the package first to get the features?

**Comment by z3bi** [comment]
@LaminT Yes, I recommend installing using the Swift Package Manager.

**Comment by LaminT** [comment]
I'm not a beginner like that. I've already built the app, just missing some features like upcoming prayer, notifications and so on..

**Comment by LaminT** [comment]
Jazâkallâhu khairan

**Comment by SNNafi** [comment]
Sorry for misunderstanding.

[Here](https://www.hackingwithswift.com/books/ios-swiftui/scheduling-local-notifications) is an article for scheduling local notification

You can get tommorrow `Date` by this code -> `Calendar.current.date(byAdding: .day, value: 1, to: Date())!`

Then, use the `Date` object to retrieve the prayer time for that day.

Good Luck

**Comment by SNNafi** [comment]
@LaminT Wa iyyaka
