### ISSUE TITLE
Changed: How to fix current prayer time?

### ISSUE THREAD

**Issue by Babyyoda777** [batoulapps/adhan-swift#75]
Is there a method to control jamat times for each prayer. I am trying to replicate the prayer timing from here: http://harrowmosque.org.uk

**Comment by z3bi** [comment]
@Babyyoda777 this library does not handle jamat/iqamah times as that is really going to be different per masjid and not something that can be calculated.

**Comment by Babyyoda777** [comment]
Okay understood, jazakallah. Then what about notifications. I cannot figure out how to make it work. Here is my implementation:`    let cal = Calendar(identifier: Calendar.Identifier.gregorian)
    let coordinates = Coordinates(latitude: 51.5806, longitude: 0.3420)
    let size = UIScreen.main.bounds
    
    @State  var sunrize : String
    @State  var fajr : String
    @State var dhuhr : String
    @State var asr : String
    @State var maghrib : String
    @State var isha : String
    @State var currentPrayer : String

    @StateObject var feedViewModel = FeedViewModel()

    func calculateTime()->Void{
        let date = cal.dateComponents([.year, .month, .day], from: Date())
        
        var params = CalculationMethod.moonsightingCommittee.params
        params.madhab = .hanafi
        params.adjustments.fajr = 5/2
        params.adjustments.sunrise = 2
        params.adjustments.dhuhr = 3
        params.adjustments.maghrib = -1
        params.adjustments.asr = 3
        params.adjustments.isha = 3
        if let prayers = PrayerTimes(coordinates: coordinates, date: date, calculationParameters: params) {
            let formatter = DateFormatter()
            formatter.timeStyle = .short
            formatter.timeZone = TimeZone(identifier: "Europe/London")!
            
            self.sunrize = formatter.string(from: prayers.sunrise)
            self.fajr = formatter.string(from: prayers.fajr)
            self.dhuhr = formatter.string(from: prayers.dhuhr)
            self.asr = formatter.string(from: prayers.asr)
            self.maghrib = formatter.string(from: prayers.maghrib)
            self.isha = formatter.string(from: prayers.isha)
            
        }
    }`



This is what I have when trying to call a notification but it just says "prayer not found"
`                                         let center = UNUserNotificationCenter.current()
                                            let content = UNMutableNotificationContent()
                                            content.title = "prayer time"
                                            content.body = "Time to pray"
                                            content.categoryIdentifier = "alarm"
                                            content.sound = UNNotificationSound.default

                                            let trigger = UNCalendarNotificationTrigger(dateMatching: prayers.fajr, repeats: false)

                                            let request = UNNotificationRequest(identifier: UUID().uuidString, content: content, trigger: trigger)
                                            center.add(request)`

**Comment by z3bi** [comment]
that's really outside of the scope of this library as well, it's not even clear in this code sample how the notification code gets access to the `prayers` struct.

**Comment by Babyyoda777** [comment]
I want to also use the current prayer time feature but I am at loss at how to implement. This is what im trying so far:
![image](https://user-images.githubusercontent.com/80623330/186188389-6e3b1aa3-9886-480b-8110-bb8e9c3057c2.png)
I get the following error

**Comment by z3bi** [comment]
`prayers.currentPrayer` returns a `Prayer` value, not a date. You would need to instead use `prayers.time(for: prayers.currentPrayer)` to get the Date associated for that Prayer.

**Comment by Babyyoda777** [comment]
![image](https://user-images.githubusercontent.com/80623330/186190270-920e0bf8-546c-45aa-a3fb-f9fc05f98a2a.png)
Is this what you mean? sorry im still a bit new to swift.

**Comment by z3bi** [comment]
Yes but you will need to unwrap the optional prayer since it can be nil sometimes.

```
if let currentPrayer = prayers.currentPrayer {
    self.current = formatter.string(from: prayers.time(for: currentPrayer))
} else {
    // if there's no current prayer then it means its between midnight and fajr. It's up to you to decide how you want to handle this situation
}
```

**Comment by Babyyoda777** [comment]
Hmm, it still gives me a circular reference error :/

**Comment by Babyyoda777** [comment]
![Screenshot 2022-08-23 at 16 03 05](https://user-images.githubusercontent.com/80623330/186193169-deb04589-945e-4228-b0c6-09b6a2770093.png)

**Comment by z3bi** [comment]
Sorry, currentPrayer is a function. Try this.

```
if let currentPrayer = prayers.currentPrayer() {
    self.current = formatter.string(from: prayers.time(for: currentPrayer))
} else {
    // if there's no current prayer then it means its between midnight and fajr.
    // It's up to you to decide how you want to handle this situation
}
```

**Comment by Babyyoda777** [comment]
THANK YOU SO MUCH, YOU HAVE MADE MY DAY. Jazakallah

**Comment by Babyyoda777** [comment]
Sorry for reopening but I this doesn't seem to work no matter what I try :/
![Screenshot 2022-08-24 at 15 12 31](https://user-images.githubusercontent.com/80623330/186441354-355f3a24-7827-48ea-b498-87c5b95fa062.png)
