### ISSUE TITLE
Finding exact prayer times

### ISSUE THREAD

**Issue by imthath-m** [batoulapps/adhan-swift#81]
What is the reason for calculating the prayer time for the next day? (as you can see [here](https://github.com/batoulapps/adhan-swift/blob/fe8381795e65dc00ca0a584a2e82058f05e371d0/Sources/PrayerTimes.swift#L57)). 

I do not have expertise with prayer times, but I am just curious as I am building my prayer times app on top of Adhan. Can you also provide reference for using the next day for calculations?

**Comment by z3bi** [comment]
That specific request is made to get the length of the night (sunset of the current day to sunrise of the next day) to use for the High Latitude Rule. This is where the latitude doesn't allow for a true Isha and Fajr calculation and instead we use the length of the night to approximate it.
